name: Deploy OSSRH Snapshot
description: Deploys OSSRH Snapshot Artifacts
inputs:
  java-version:
    description: Java version
    required: false
    default: "11"
  java-distribution:
    description: Java distribution
    required: false
    default: zulu
  ossrh-username:
    description: OSSRH username
    required: true
  ossrh-password:
    description: OSSRH password
    required: true
  code-signing-private-key:
    description: Code signing GPG private key
    required: true
  code-signing-private-key-fingerprint:
    description: Code signing GPG private key fingerprint
    required: true
  code-signing-private-key-passphrase:
    description: Code signing GPG private key passphrase
    required: true
runs:
  using: composite
  steps:
    - name: Setup Runtime Environment
      uses: ./actions/setup-runtime
      with:
        java-version: ${{inputs.java-version}}
        java-distribution: ${{inputs.java-distribution}}
        code-signing-private-key: ${{inputs.code-signing-private-key}}
    - name: Deploy Snapshot Artifacts
      env:
        CODE_SIGNING_KEY_FINGERPRINT: ${{inputs.code-signing-private-key-fingerprint}}
        CODE_SIGNING_KEY_PASSPHRASE: ${{inputs.code-signing-private-key-passphrase}}
        OSSRH_USERNAME: ${{inputs.ossrh-username}}
        OSSRH_PASSWORD: ${{inputs.ossrh-password}}
      shell: bash
      run: scripts/deploy-snapshot.sh
