name: Setup Runtime Environment
description: Prepares the runtime environment for deploying OSSRH artifacts
inputs:
  java-version:
    description: Java version
    required: false
    default: "11"
  java-distribution:
    description: Java distribution
    required: false
    default: zulu
  ossrh-username-env-variable:
    description: Name of the environment variable containing the OSSRH username
    required: false
    default: OSSRH_USERNAME
  ossrh-password-env-variable:
    description: Name of the environment variable containing the OSSRH password
    required: false
    default: OSSRH_PASSWORD
  code-signing-private-key:
    description: Code signing GPG private key
    required: false
  code-signing-private-key-passphrase-env-variable:
    description: Name of the environment variable containing code signing GPG private key passphrase
    required: false
    default: CODE_SIGNING_KEY_PASSPHRASE
runs:
  using: composite
  steps:
    - name: Set up basic runtime environment
      if: ${{!inputs.code-signing-private-key}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.java-distribution}}
        cache: maven
    - name: Set up OSSRH deployment environment
      if: ${{inputs.code-signing-private-key}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.java-distribution}}
        cache: maven
        gpg-private-key: ${{inputs.code-signing-private-key}}
        gpg-passphrase: ${{inputs.code-signing-private-key-passphrase-env-variable}}
        server-id: ossrh
        server-username: ${{inputs.ossrh-username-env-variable}}
        server-password: ${{inputs.ossrh-password-env-variable}}
