name: Branch Build
on:
  push:
    branches:
      - feature/**
      - fix/**
  pull_request:
    branches:
      - master
      - feature/**
      - fix/**
jobs:
  branch-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Branch
        uses: ./actions/build-branch

