name: OSSRH Snapshot
on:
  push:
    branches:
      - master
jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Snapshot Artifacts
        uses: ./.github/actions/deploy-ossrh-snapshot
        with:
          code-signing-private-key: ${{secrets.CODE_SIGNING_KEY}}
          code-signing-private-key-fingerprint: ${{secrets.CODE_SIGNING_KEY_FINGERPRINT}}
          code-signing-private-key-passphrase: ${{secrets.CODE_SIGNING_KEY_PASSPHRASE}}
          ossrh-username: ${{secrets.OSSRH_USERNAME}}
          ossrh-password: ${{secrets.OSSRH_PASSWORD}}